from enum import Enum


class RiskSeverity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskFlag(str, Enum):
    # High Confidence Signals
    PAYMENT_REQUESTED = "PAYMENT_REQUESTED"
    SECURITY_DEPOSIT_REQUESTED = "SECURITY_DEPOSIT_REQUESTED"
    TRAINING_FEE_REQUESTED = "TRAINING_FEE_REQUESTED"
    EMAIL_DOMAIN_MISMATCH = "EMAIL_DOMAIN_MISMATCH"
    BROKEN_WEBSITE = "BROKEN_WEBSITE"
    NO_CONTACT_INFORMATION = "NO_CONTACT_INFORMATION"

    # Medium Confidence Signals
    FREE_EMAIL_RECRUITER = "FREE_EMAIL_RECRUITER"
    NO_LINKEDIN_PRESENCE = "NO_LINKEDIN_PRESENCE"
    NO_COMPANY_ADDRESS = "NO_COMPANY_ADDRESS"
    NO_CAREERS_PAGE = "NO_CAREERS_PAGE"

    # Low Confidence Signals
    NEW_DOMAIN = "NEW_DOMAIN"
    RARE_TLD = "RARE_TLD"
    GRAMMAR_ISSUES = "GRAMMAR_ISSUES"
    MISSING_SOCIAL_LINKS = "MISSING_SOCIAL_LINKS"

    # Domain Age unknown marker
    DOMAIN_AGE_UNKNOWN = "DOMAIN_AGE_UNKNOWN"
