"""add_integrity_fields

Revision ID: 2796f446c54d
Revises: b1b33e037e4d
Create Date: 2026-06-15 17:04:18.886742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2796f446c54d'
down_revision: Union[str, Sequence[str], None] = 'b1b33e037e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.add_column('uploaded_files', sa.Column('upload_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'upload_timestamp')
    op.drop_column('uploaded_files', 'sha256')
    # ### end Alembic commands ###
