"""update_scan_model

Revision ID: 2a209d4ceaa0
Revises: 2796f446c54d
Create Date: 2026-06-15 17:19:17.946738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a209d4ceaa0'
down_revision: Union[str, Sequence[str], None] = '2796f446c54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('scan_type', sa.String(length=50), nullable=False))
    op.add_column('scans', sa.Column('scan_version', sa.String(length=10), nullable=False))
    op.add_column('scans', sa.Column('scan_source', sa.String(length=50), nullable=False))
    op.add_column('scans', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('scans', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('scans', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scans', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scans', sa.Column('error_code', sa.String(length=50), nullable=True))
    op.add_column('scans', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_scan_type'), 'scans', ['scan_type'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    op.drop_column('scans', 'input_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('input_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_scan_type'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_column('scans', 'error_message')
    op.drop_column('scans', 'error_code')
    op.drop_column('scans', 'completed_at')
    op.drop_column('scans', 'started_at')
    op.drop_column('scans', 'retry_count')
    op.drop_column('scans', 'priority')
    op.drop_column('scans', 'scan_source')
    op.drop_column('scans', 'scan_version')
    op.drop_column('scans', 'scan_type')
    # ### end Alembic commands ###
