"""add_company_verifications

Revision ID: 6c6f5fbd3860
Revises: 04cdf5f568f8
Create Date: 2026-06-16 04:05:46.707784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6f5fbd3860'
down_revision: Union[str, Sequence[str], None] = '04cdf5f568f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('verification_score', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_level', sa.String(length=50), nullable=False),
    sa.Column('verification_confidence', sa.String(length=20), nullable=False),
    sa.Column('verification_version', sa.String(length=20), nullable=False),
    sa.Column('verification_source', sa.String(length=100), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_verification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_verification_breakdowns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('score_change', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source_reliability', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['company_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_verification_breakdowns_verification_id'), 'company_verification_breakdowns', ['verification_id'], unique=False)
    op.create_table('company_verification_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['company_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_verification_evidence_verification_id'), 'company_verification_evidence', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_verification_evidence_verification_id'), table_name='company_verification_evidence')
    op.drop_table('company_verification_evidence')
    op.drop_index(op.f('ix_company_verification_breakdowns_verification_id'), table_name='company_verification_breakdowns')
    op.drop_table('company_verification_breakdowns')
    op.drop_table('company_verifications')
    # ### end Alembic commands ###
