"""add_recruiter_verifications

Revision ID: 709cd6bd3730
Revises: 9fec8e4da9c6
Create Date: 2026-06-16 13:40:32.507705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709cd6bd3730'
down_revision: Union[str, Sequence[str], None] = '9fec8e4da9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter_reputation_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recruiter_email', sa.String(length=255), nullable=False),
    sa.Column('claimed_company', sa.String(length=255), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=False),
    sa.Column('verification_level', sa.String(length=50), nullable=False),
    sa.Column('recruiter_verification_count', sa.Integer(), nullable=False),
    sa.Column('recruiter_success_rate', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_reputation_snapshots_recruiter_email'), 'recruiter_reputation_snapshots', ['recruiter_email'], unique=False)
    op.create_table('recruiter_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recruiter_name', sa.String(length=255), nullable=False),
    sa.Column('recruiter_email', sa.String(length=255), nullable=False),
    sa.Column('claimed_company', sa.String(length=255), nullable=False),
    sa.Column('recruiter_phone', sa.String(length=50), nullable=True),
    sa.Column('recruiter_role', sa.String(length=100), nullable=True),
    sa.Column('linkedin_profile_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_validation_status', sa.String(length=50), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_level', sa.String(length=50), nullable=False),
    sa.Column('verification_confidence', sa.String(length=20), nullable=False),
    sa.Column('email_domain_status', sa.String(length=50), nullable=False),
    sa.Column('company_match_status', sa.String(length=50), nullable=False),
    sa.Column('phone_match_status', sa.String(length=50), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_verifications_claimed_company'), 'recruiter_verifications', ['claimed_company'], unique=False)
    op.create_index(op.f('ix_recruiter_verifications_recruiter_email'), 'recruiter_verifications', ['recruiter_email'], unique=False)
    op.create_table('recruiter_verification_breakdowns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source_reliability', sa.String(length=20), nullable=False),
    sa.Column('score_change', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['recruiter_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_verification_breakdowns_verification_id'), 'recruiter_verification_breakdowns', ['verification_id'], unique=False)
    op.create_table('recruiter_verification_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['recruiter_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_verification_evidence_verification_id'), 'recruiter_verification_evidence', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruiter_verification_evidence_verification_id'), table_name='recruiter_verification_evidence')
    op.drop_table('recruiter_verification_evidence')
    op.drop_index(op.f('ix_recruiter_verification_breakdowns_verification_id'), table_name='recruiter_verification_breakdowns')
    op.drop_table('recruiter_verification_breakdowns')
    op.drop_index(op.f('ix_recruiter_verifications_recruiter_email'), table_name='recruiter_verifications')
    op.drop_index(op.f('ix_recruiter_verifications_claimed_company'), table_name='recruiter_verifications')
    op.drop_table('recruiter_verifications')
    op.drop_index(op.f('ix_recruiter_reputation_snapshots_recruiter_email'), table_name='recruiter_reputation_snapshots')
    op.drop_table('recruiter_reputation_snapshots')
    # ### end Alembic commands ###
