"""add_domain_verifications

Revision ID: 9fec8e4da9c6
Revises: 6c6f5fbd3860
Create Date: 2026-06-16 13:07:12.450590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fec8e4da9c6'
down_revision: Union[str, Sequence[str], None] = '6c6f5fbd3860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_reputation_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=False),
    sa.Column('verification_level', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_reputation_snapshots_domain'), 'domain_reputation_snapshots', ['domain'], unique=False)
    op.create_table('domain_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_level', sa.String(length=50), nullable=False),
    sa.Column('verification_confidence', sa.String(length=20), nullable=False),
    sa.Column('dns_status', sa.String(length=50), nullable=False),
    sa.Column('mx_status', sa.String(length=50), nullable=False),
    sa.Column('spf_status', sa.String(length=50), nullable=False),
    sa.Column('dmarc_status', sa.String(length=50), nullable=False),
    sa.Column('dkim_status', sa.String(length=50), nullable=False),
    sa.Column('ssl_status', sa.String(length=50), nullable=False),
    sa.Column('certificate_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_verification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_verifications_domain'), 'domain_verifications', ['domain'], unique=False)
    op.create_table('domain_verification_breakdowns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source_reliability', sa.String(length=20), nullable=False),
    sa.Column('score_change', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['domain_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_verification_breakdowns_verification_id'), 'domain_verification_breakdowns', ['verification_id'], unique=False)
    op.create_table('domain_verification_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['domain_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_verification_evidence_verification_id'), 'domain_verification_evidence', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_verification_evidence_verification_id'), table_name='domain_verification_evidence')
    op.drop_table('domain_verification_evidence')
    op.drop_index(op.f('ix_domain_verification_breakdowns_verification_id'), table_name='domain_verification_breakdowns')
    op.drop_table('domain_verification_breakdowns')
    op.drop_index(op.f('ix_domain_verifications_domain'), table_name='domain_verifications')
    op.drop_table('domain_verifications')
    op.drop_index(op.f('ix_domain_reputation_snapshots_domain'), table_name='domain_reputation_snapshots')
    op.drop_table('domain_reputation_snapshots')
    # ### end Alembic commands ###
