"""add_file_hardening_fields

Revision ID: b1b33e037e4d
Revises: bc5e83155762
Create Date: 2026-06-15 17:03:34.937082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b33e037e4d'
down_revision: Union[str, Sequence[str], None] = 'bc5e83155762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('virus_scan_status', sa.String(length=50), nullable=False))
    op.add_column('uploaded_files', sa.Column('virus_scan_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('uploaded_files', sa.Column('virus_scan_engine', sa.String(length=100), nullable=True))
    op.add_column('uploaded_files', sa.Column('duplicate_of', sa.Uuid(), nullable=True))
    op.add_column('uploaded_files', sa.Column('document_type', sa.String(length=50), nullable=False))
    op.add_column('uploaded_files', sa.Column('integrity_status', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'uploaded_files', 'uploaded_files', ['duplicate_of'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.drop_column('uploaded_files', 'integrity_status')
    op.drop_column('uploaded_files', 'document_type')
    op.drop_column('uploaded_files', 'duplicate_of')
    op.drop_column('uploaded_files', 'virus_scan_engine')
    op.drop_column('uploaded_files', 'virus_scan_date')
    op.drop_column('uploaded_files', 'virus_scan_status')
    # ### end Alembic commands ###
