"""add report persistence enterprise architecture

Revision ID: b52c5507fbfa
Revises: 2a209d4ceaa0
Create Date: 2026-06-15 22:12:54.736790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52c5507fbfa'
down_revision: Union[str, Sequence[str], None] = '2a209d4ceaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_history_report_id'), 'report_history', ['report_id'], unique=False)
    op.add_column('evidence_items', sa.Column('evidence_type', sa.String(length=100), nullable=False))
    op.add_column('evidence_items', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('evidence_items', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('evidence_items', sa.Column('source_reference', sa.String(length=512), nullable=True))
    op.add_column('evidence_items', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('evidence_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('evidence_items', 'dimension')
    op.add_column('reports', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('reports', sa.Column('report_version', sa.String(length=10), nullable=False))
    op.add_column('reports', sa.Column('report_status', sa.String(length=50), nullable=False))
    op.add_column('reports', sa.Column('risk_score', sa.Float(), nullable=False))
    op.add_column('reports', sa.Column('risk_level', sa.String(length=50), nullable=False))
    op.add_column('reports', sa.Column('recommendation', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('reports', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('generated_by', sa.String(length=50), nullable=False))
    op.add_column('reports', sa.Column('generation_engine', sa.String(length=100), nullable=True))
    op.add_column('reports', sa.Column('generation_version', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('reports_scan_id_key'), 'reports', type_='unique')
    op.create_index('idx_reports_scan_status', 'reports', ['scan_id', 'report_status'], unique=False)
    op.create_index('idx_reports_status_created', 'reports', ['report_status', 'created_at'], unique=False)
    op.create_index('idx_reports_user_created', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_report_status'), 'reports', ['report_status'], unique=False)
    op.create_index(op.f('ix_reports_risk_score'), 'reports', ['risk_score'], unique=False)
    op.create_index(op.f('ix_reports_scan_id'), 'reports', ['scan_id'], unique=False)
    op.create_index(op.f('ix_reports_trust_score'), 'reports', ['trust_score'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.drop_constraint(op.f('reports_scan_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'scans', ['scan_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_scan_id_fkey'), 'reports', 'scans', ['scan_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_trust_score'), table_name='reports')
    op.drop_index(op.f('ix_reports_scan_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_risk_score'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index('idx_reports_user_created', table_name='reports')
    op.drop_index('idx_reports_status_created', table_name='reports')
    op.drop_index('idx_reports_scan_status', table_name='reports')
    op.create_unique_constraint(op.f('reports_scan_id_key'), 'reports', ['scan_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('reports', 'generation_version')
    op.drop_column('reports', 'generation_engine')
    op.drop_column('reports', 'generated_by')
    op.drop_column('reports', 'deleted_at')
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'generated_at')
    op.drop_column('reports', 'recommendation')
    op.drop_column('reports', 'risk_level')
    op.drop_column('reports', 'risk_score')
    op.drop_column('reports', 'report_status')
    op.drop_column('reports', 'report_version')
    op.drop_column('reports', 'user_id')
    op.add_column('evidence_items', sa.Column('dimension', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('evidence_items', 'deleted_at')
    op.drop_column('evidence_items', 'is_deleted')
    op.drop_column('evidence_items', 'source_reference')
    op.drop_column('evidence_items', 'confidence')
    op.drop_column('evidence_items', 'title')
    op.drop_column('evidence_items', 'evidence_type')
    op.drop_index(op.f('ix_report_history_report_id'), table_name='report_history')
    op.drop_table('report_history')
    # ### end Alembic commands ###
