'use client';

import { Brain } from 'lucide-react';

interface AIAnalysisProps {
  summary: string;
}

function renderMarkdown(text: string): React.ReactNode[] {
  const lines = text.split('\n');
  const elements: React.ReactNode[] = [];
  let listItems: string[] = [];
  let listKey = 0;

  const flushList = () => {
    if (listItems.length > 0) {
      elements.push(
        <ul
          key={`list-${listKey++}`}
          className="space-y-2 my-3 ml-4"
        >
          {listItems.map((item, i) => (
            <li
              key={i}
              className="text-sm leading-relaxed flex gap-2"
              style={{ color: 'var(--text-secondary)' }}
            >
              <span className="shrink-0 mt-1.5 w-1.5 h-1.5 rounded-full bg-primary" />
              <span>{renderInline(item)}</span>
            </li>
          ))}
        </ul>
      );
      listItems = [];
    }
  };

  const renderInline = (line: string): React.ReactNode => {
    const parts: React.ReactNode[] = [];
    const regex = /\*\*(.+?)\*\*/g;
    let lastIndex = 0;
    let match;

    while ((match = regex.exec(line)) !== null) {
      if (match.index > lastIndex) {
        parts.push(line.slice(lastIndex, match.index));
      }
      parts.push(
        <strong key={match.index} style={{ color: 'var(--text-primary)', fontWeight: 600 }}>
          {match[1]}
        </strong>
      );
      lastIndex = regex.lastIndex;
    }

    if (lastIndex < line.length) {
      parts.push(line.slice(lastIndex));
    }

    return parts.length > 0 ? parts : line;
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    if (!line) {
      flushList();
      continue;
    }

    if (line.startsWith('### ')) {
      flushList();
      elements.push(
        <h3
          key={`h3-${i}`}
          className="text-base font-bold mt-6 mb-2"
          style={{ color: '#818cf8' }}
        >
          {line.replace('### ', '')}
        </h3>
      );
      continue;
    }

    if (line.startsWith('## ')) {
      flushList();
      elements.push(
        <h2
          key={`h2-${i}`}
          className="text-lg font-bold mt-6 mb-3"
          style={{ color: '#818cf8' }}
        >
          {line.replace('## ', '')}
        </h2>
      );
      continue;
    }

    const numberedMatch = line.match(/^\d+\.\s+(.+)/);
    if (numberedMatch) {
      listItems.push(numberedMatch[1]);
      continue;
    }

    if (line.startsWith('- ') || line.startsWith('* ')) {
      listItems.push(line.slice(2));
      continue;
    }

    flushList();
    elements.push(
      <p
        key={`p-${i}`}
        className="text-sm leading-relaxed my-2"
        style={{ color: 'var(--text-secondary)' }}
      >
        {renderInline(line)}
      </p>
    );
  }

  flushList();
  return elements;
}

export default function AIAnalysis({ summary }: AIAnalysisProps) {
  return (
    <div
      className="rounded-xl overflow-hidden"
      style={{
        background: 'var(--bg-card)',
        border: '1px solid var(--border-primary)',
      }}
    >
      <div
        className="flex items-center gap-3 px-6 py-4"
        style={{ borderBottom: '1px solid var(--border-primary)' }}
      >
        <div
          className="w-9 h-9 rounded-lg flex items-center justify-center"
          style={{ background: 'rgba(99, 102, 241, 0.12)' }}
        >
          <Brain size={18} style={{ color: '#6366f1' }} />
        </div>
        <div>
          <h3 className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>
            AI Investigation Summary
          </h3>
          <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>
            Generated by LEGITIFY AI agents
          </p>
        </div>
      </div>

      <div className="px-6 py-5">
        {renderMarkdown(summary)}
      </div>
    </div>
  );
}
